# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 7) do

  create_table "note_files", :force => true do |t|
    t.column "note_id",    :integer
    t.column "filename",   :string
    t.column "systempath", :string
    t.column "filetype",   :string
  end

  create_table "notes", :force => true do |t|
    t.column "user_id",     :integer
    t.column "description", :text
    t.column "date",        :date
    t.column "favorite",    :integer
    t.column "color",       :string
    t.column "x",           :integer
    t.column "y",           :integer
    t.column "z",           :integer
  end

  create_table "taggings", :force => true do |t|
    t.column "taggable_id",   :integer
    t.column "tag_id",        :integer
    t.column "taggable_type", :string
  end

  create_table "tags", :force => true do |t|
    t.column "name", :string
  end

  create_table "users", :force => true do |t|
    t.column "login",    :string
    t.column "password", :string
  end

end
