# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 3) do

  create_table "attachments", :force => true do |t|
    t.column "attachable_id",   :integer
    t.column "attachable_type", :string
    t.column "type",            :string
    t.column "name",            :string
    t.column "content_type",    :string
    t.column "date",            :datetime
    t.column "clear_text",      :text
    t.column "data",            :binary
  end

  create_table "people", :force => true do |t|
    t.column "user_id",    :integer
    t.column "first_name", :string
    t.column "last_name",  :string
    t.column "title",      :string
    t.column "address1",   :string
    t.column "address2",   :string
    t.column "city",       :string
    t.column "state",      :string
    t.column "postal",     :string
    t.column "country",    :string
  end

  create_table "users", :force => true do |t|
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
  end

end
