# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 13) do

  create_table "log_entries", :force => true do |t|
    t.column "running_log_id", :integer, :default => 0
    t.column "date",           :date
    t.column "miles",          :float,   :default => 0.0
    t.column "time",           :integer, :default => 0
    t.column "comments",       :text
  end

  create_table "logs", :force => true do |t|
  end

  create_table "running_logs", :force => true do |t|
    t.column "user_id",     :integer, :default => 0
    t.column "schedule_id", :integer, :default => 0
    t.column "description", :string
  end

  create_table "schedule_entries", :force => true do |t|
    t.column "schedule_id", :integer, :default => 0
    t.column "date",        :date
    t.column "miles",       :integer, :default => 0
    t.column "time",        :integer, :default => 0
    t.column "comments",    :text
  end

  create_table "schedules", :force => true do |t|
    t.column "description",    :string
    t.column "running_log_id", :integer
  end

  create_table "users", :force => true do |t|
    t.column "login",      :string
    t.column "password",   :string
    t.column "first_name", :string
    t.column "last_name",  :string
    t.column "gender",     :string
    t.column "birthday",   :integer
    t.column "bio",        :text
    t.column "email",      :string
  end

  create_table "weekly_comments", :force => true do |t|
    t.column "log_id",   :integer, :default => 0
    t.column "comments", :text
  end

end
